# Generated by Django 4.0 on 2022-01-02 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discussion', '0003_alter_reply_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='user1',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
