# Generated by Django 4.0 on 2021-12-28 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistics',
            name='accepted_answer_count',
        ),
    ]
